/**
 * Amplify Configuration
 * This file will be populated with amplify_outputs.json after backend deployment
 */

// Try to load amplify_outputs.json (generated after backend deployment)
// In production, this file will be generated by Amplify Console
let amplifyConfig: any = null;

// Check if we're in a build environment where amplify_outputs.json might be available
// For now, we'll check at runtime in the browser
if (typeof window !== 'undefined') {
  // In the browser, we'll check for the config via a fetch or it will be injected
  // For now, we'll rely on the backend being deployed and the file being available
}

export default amplifyConfig;

