import React from 'react';
import ReactDOM from 'react-dom/client';
import { Amplify } from 'aws-amplify';
import './index.css';
import App from './App';
import { AuthProvider } from './hooks/useAuth';

// Configure Amplify - will be populated after first deployment
// Note: amplify_outputs.json will be generated by Amplify Console after backend deployment
// For now, we'll configure it dynamically if it exists
try {
  // Amplify Console will inject amplify_outputs.json during build
  // This will be available at runtime, not build time
  const outputs = require('./amplify_outputs.json');
  Amplify.configure(outputs);
  console.log('✅ Amplify backend configured successfully');
} catch (error) {
  // If file doesn't exist yet, app will work in demo mode
  console.warn('⚠️ Amplify outputs not found - running in demo mode.');
  console.warn('Backend needs to be deployed in Amplify Console to generate amplify_outputs.json');
}

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);
root.render(
  <React.StrictMode>
    <AuthProvider>
      <App />
    </AuthProvider>
  </React.StrictMode>
); 