import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';
import { AuthProvider } from './hooks/useAuth';

// Configure Amplify if backend is deployed
// The amplify_outputs.json will be generated by Amplify Console after backend deployment
// For now, we'll run in demo mode with localStorage
try {
  // Try to dynamically import amplify_outputs.json if it exists
  // This will only work after backend is deployed
  // In production, Amplify Console will inject this file during build
  const amplifyConfig = require('../amplify_outputs.json');
  if (amplifyConfig) {
    try {
      const { Amplify } = require('aws-amplify');
      Amplify.configure(amplifyConfig);
      console.log('Amplify backend configured successfully');
    } catch (error) {
      console.log('Amplify package not available');
    }
  }
} catch (error) {
  // File doesn't exist yet - running in demo mode
  // This is expected until backend is deployed
  console.log('Running in demo mode - Amplify backend not yet deployed');
}

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);
root.render(
  <React.StrictMode>
    <AuthProvider>
      <App />
    </AuthProvider>
  </React.StrictMode>
); 