import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';
import { AuthProvider } from './hooks/useAuth';
import { Amplify } from 'aws-amplify';

// Configure Amplify Gen 2 backend
// The amplify_outputs.json will be generated by:
// 1. Amplify Console after deployment (production)
// 2. Cloud sandbox (npx ampx sandbox) for local development
try {
  // Try to import amplify_outputs.json using ES6 import
  // Try src folder first, then parent directory
  let amplifyConfig: any;
  try {
    amplifyConfig = require('./amplify_outputs.json');
  } catch {
    try {
      amplifyConfig = require('../amplify_outputs.json');
    } catch {
      throw new Error('amplify_outputs.json not found');
    }
  }
  
  if (amplifyConfig && amplifyConfig.auth) {
    // Configure Amplify with Gen 2 outputs format
    // Gen 2 outputs.json format is directly compatible with Amplify v6
    try {
      // Log config structure for debugging
      console.log('📋 Config structure:', {
        hasAuth: !!amplifyConfig.auth,
        hasData: !!amplifyConfig.data,
        userPoolId: amplifyConfig.auth?.user_pool_id,
        version: amplifyConfig.version
      });
      
      // Configure Amplify - Gen 2 format works directly
      Amplify.configure(amplifyConfig);
      
      console.log('✅ Amplify.configure() called successfully');
      console.log('   User Pool:', amplifyConfig.auth.user_pool_id);
      console.log('   Region:', amplifyConfig.auth.aws_region);
      console.log('   Client ID:', amplifyConfig.auth.user_pool_client_id);
      
      // Give Amplify time to process the Gen 2 config format
      // Amplify v6 needs time to transform Gen 2 format internally
      setTimeout(() => {
        console.log('✅ Amplify Gen 2 backend configured successfully');
        console.log('   Ready for authentication operations');
      }, 3000); // Increased to 3 seconds for Gen 2 config processing
    } catch (configureError: any) {
      console.error('❌ Error configuring Amplify:', configureError);
      throw configureError;
    }
  } else {
    throw new Error('Config file missing auth section');
  }
} catch (error: any) {
  // File doesn't exist yet - running in demo mode with localStorage
  // To connect to backend:
  // 1. Download amplify_outputs.json from Amplify Console, OR
  // 2. Run: npx ampx sandbox (from root directory)
  console.warn('⚠️ Running in demo mode - Amplify backend not connected');
  console.warn('   To connect: Download amplify_outputs.json or run: npx ampx sandbox');
  if (error?.message) {
    console.warn('   Error:', error.message);
  }
}

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);
root.render(
  <React.StrictMode>
    <AuthProvider>
      <App />
    </AuthProvider>
  </React.StrictMode>
); 